### ISSUE TITLE
Transparency and Brush Toggle Key/Shortcuts

### ISSUE THREAD

**Issue by 0xvividmirage** [econtrerasd/F256-GraphicToolkit#4]
It feels natural to switch between erasing and using the pencil tool when drawing sprites. My suggestion is to have shortcut that toggles between drawing with the last color selected and the transparency "color". 

My suggestion is:
"P" Key = Pencil/Draw Tool with last color selected
"E" Key = Eraser/Transparency Tool

Alternately:
Press "P" Twice = Toggle between the Draw Tool and Eraser/Transparency tool.

I actually like the alternate better because it feels a bit more modern.

**Comment by econtrerasd** [comment]
Well technically there is no eraser tool, since the pencil always paints
with the selected color, for erasing you just draw using the transparent
color..
For this scenario the program supports the "Space" key, which works as an
eyedropper tool in other packages, so you can press it over an empty box to
select the transparent color.
If you are using the mouse, the alternate mouse button has the same
function.

Try it and if this wont work for a reason would be happy to address this

**Comment by 0xvividmirage** [comment]
I'm aware that the pencil tool is just using index 0 to erase or act as an eraser tool.

I'm aware of the spacebar function, but I wasn't aware of the right click having the same function. This is better for the act of really detailing something. I still think having a way to toggle between color 0 and the last selected color would be a nice feature, but for now, right click to grab the color/transparency is OK.
